# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: ci
        run: yarn ci
        working-directory: ./
      - name: build
        run: yarn run build --if-present
        working-directory: ./
      - name: test
        run: yarn run test:ci
        working-directory: ./
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NEXT_PUBLIC_API_MOCKING: enabled
        with:
          build: yarn run build
          start: yarn start -p 3000
